---
title: "dada2 auto `r Sys.Date()`"
author: "Florentin CONSTANCIAS"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 4
---


```{r setup, include=FALSE}
rm(list = ls())

knitr::opts_chunk$set(echo = TRUE)
DT::datatable(matrix())
```

```{r install, include=TRUE}
# install.packages("devtools")
# 
# install.packages("optparse")
#
# devtools::install_github("tidyverse/tidyverse")
#
# if (!requireNamespace("BiocManager", quietly = TRUE))
#     install.packages("BiocManager")
# 
# BiocManager::install("ShortRead")
# 
# BiocManager::install("DECIPHER")
#
# BiocManager::install("phyloseq")
#
# devtools::install_github("KlausVigo/phangorn")
# 
# devtools::install_github("benjjneb/dada2", ref="v1.18") # change the ref argument to get other versions
# 
```

```{bash engine.opts='-l'}
conda activate metabarcodingRpipeline
```


```{bash engine.opts='-l'}
Rscript scripts/dada2_metabarcoding_pipeline.R --help
```


```{bash engine.opts='-l', results = "hide"}
Rscript scripts/dada2_metabarcoding_pipeline.R \
-i /Users/fconstan/Documents/GitHub/metabarcodingRpipeline/test-data/ \
--atropos_binary /Users/fconstan/miniconda3/envs/metabarcodingRpipeline/bin/atropos \
--preset V3V4 \
--nbases 10 \
-T 8 \
--collapseNoMis FALSE \
--export FALSE \
--save_out test_pipe_Rscript \
-f scripts/functions_export_simplified.R

```

```{r, results=FALSE, warning=FALSE, include=FALSE}
require(tidyverse); packageVersion("tidyverse")
```

```{r packages, results=FALSE, warning=FALSE, include=FALSE}
"dada2/dada2_pipe_out.RDS" %>%
  readRDS() -> out
```


```{r, message = FALSE, warning = FALSE, results = FALSE, results= TRUE}
out$qplot
```

```{r, message = TRUE, warning = FALSE, results = TRUE}
out$filtering_denoising$out_fwd
```
```{r, message = TRUE, warning = FALSE, results = TRUE}
out$filtering_denoising$out_rev
```

```{r, message = TRUE, warning = FALSE, results = TRUE}
out$merging$plot
```

```{r, message = TRUE, warning = FALSE, results = TRUE}
out$merging$track %>%
  DT::datatable()
```

```{r, message = TRUE, warning = FALSE, results = TRUE}
out$physeq
```

```{r, message = TRUE, warning = FALSE, results = TRUE}
source("https://raw.githubusercontent.com/fconstancias/DivComAnalyses/master/R/phyloseq_normalisation.R")

out$physeq %>%
  phyloseq_check_lib_size(data_color = "varA",
                          data_facet = "varB",
                          nreads_display = 100,
                          first_n = 5)
```
```{bash engine.opts='-l'}
Rscript scripts/run_dada2_mergeRuns_removeBimeraDenovo.R --help

```

```{bash engine.opts='-l', results = "hide"}
Rscript scripts/run_dada2_mergeRuns_removeBimeraDenovo.R \
--filt_dir dada2/02_dada2_filtered_denoised_merged/ \
-T 8 \
--trim_length 350,475 \
--collapseNoMis FALSE \
--export TRUE \
-f scripts/functions_export_simplified.R

```

```{r, message = TRUE, warning = FALSE, results = TRUE}
sessionInfo()
```

